package jdbcdemo.dao;

import java.sql.Connection;
import java.sql.SQLException;

import jdbcdemo.dao.mappers.ResultSetMapper;
import jdbcdemo.domain.Car;

public class CarRepository extends RepositoryBase<Car> {
	
	public CarRepository(Connection connection, ResultSetMapper<Car> mapper) throws SQLException{
		super(connection, mapper);
	}
	
	@Override
	protected String tableName() {
		return "cars";
	}
	
	@Override
	protected String createTableSql() {
		return "CREATE TABLE cars("
				+ "id INT GENERATED BY DEFAULT AS IDENTITY,"
				+ "brand VARCHAR(20),"
				+ "registration VARCHAR(10)"
				+ ")";
	}
	
	@Override
	protected String insertSql() {
		return "INSERT INTO cars(brand,registration) VALUES (?,?)";
	}
	
	@Override
	protected String updateSql() {
		return "UPDATE cars SET (brand, registration) = (?,?) WHERE id=?";
	}
	
	@Override
	protected String deleteSql() {
		return "DELETE FROM cars WHERE id=?";
	}
	
	@Override
	protected String selectAllSql() {
		return "SELECT * FROM cars";
	}

	@Override
	protected void setupInsert(Car entity) throws SQLException {
		insert.setString(1, entity.getBrand());
		insert.setString(2, entity.getRegistration());
	}

	@Override
	protected void setupUpdate(Car entity) throws SQLException {
		update.setString(1, entity.getBrand());
		update.setString(2, entity.getRegistration());
		update.setInt(3, entity.getId());
		update.executeUpdate();
	}
}
